#######################
# CSS-BOT CONFIG FILE #
#######################

# Discord bot credentials and settings
[discord]
token = "DISCORD-BOT-TOKEN"

# Server settings
[server]
cmd-prefix = "!"
#Message cleanup intervall (Units: d - Days, h - Hours, min - Minutes, s - Seconds, ms - Millieseconds)
cleanup-intervall = "1h"

#Color shemes
[colors]
[colors.embed]
color = "#550C18"